// Generates tiny blurred previews for next/image `placeholder="blur"`.
// Run after adding or replacing photos: `pnpm images:blur`
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const sharp = require("sharp");

const dir = path.resolve("public/images");
const photos = fs
  .readdirSync(dir)
  .filter((f) => /\.(png|jpe?g)$/i.test(f) && !f.startsWith("ornament-"))
  .sort();

const entries = [];
for (const file of photos) {
  const buf = await sharp(path.join(dir, file)).resize(12, 12, { fit: "inside" }).webp({ quality: 40 }).toBuffer();
  entries.push(`  "/images/${file}": "data:image/webp;base64,${buf.toString("base64")}",`);
}

const out = `// Generated by scripts/generate-blur.mjs. Do not edit by hand.
export const blurData: Record<string, string> = {
${entries.join("\n")}
};

/** Spread onto next/image to get a blurred preview while the real image loads. */
export function blurProps(src: string) {
  const blurDataURL = blurData[src];
  return blurDataURL ? ({ placeholder: "blur", blurDataURL } as const) : {};
}
`;
fs.writeFileSync(path.resolve("src/lib/blur-data.ts"), out);
console.log(`Wrote ${entries.length} placeholders to src/lib/blur-data.ts`);
